apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : kafka
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: kafkakeeper
  sources:

    # - repoURL: https://github.com/YURIIOZHHO/zookeeper-and-kafka.git
    #   targetRevision: main
    #   ref: values

    # - chart: kafka
    #   repoURL: https://charts.bitnami.com/bitnami
    #   targetRevision: 32.4.*
    #   helm:
    #     releaseName: kafka
    #     valueFiles:
    #       - $values/charts/kafka/dev/values_dev.yaml

    - chart: strimzi-kafka-operator
      repoURL: https://strimzi.io/charts
      targetRevision: 0.50.*
      # helm:
      #   releaseName: kafka
      #   valueFiles:
      #     - $values/charts/kafka/dev/values_dev.yaml

    - repoURL: https://github.com/YURIIOZHHO/zookeeper-and-kafka.git
      path: charts/kafka/dev/
      targetRevision: main
      ref: values
    
    - chart: kafka-ui
      repoURL: https://ui.charts.kafbat.io/
      targetRevision: 1.6.0
      helm:
        releaseName: kafka-ui
        values: |
          yamlConfig:
            kafka:
              clusters:
                - name: local
                  bootstrap-servers: my-cluster-kafka-bootstrap.kafkakeeper.svc:9092
                  read-only: true
          

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true